# Usa uma imagem oficial Node.js como base
FROM node:18-alpine

# Define o diretório de trabalho no container
WORKDIR /usr/src/app

# Copia os arquivos de configuração do projeto
COPY package*.json ./

# Instala as dependências do projeto
RUN npm install

# Copia o código da aplicação
COPY fraud_sdk_backend.js ./

# Expõe a porta em que a aplicação vai rodar
EXPOSE 3000

# Comando para iniciar o servidor
CMD [ "npm", "start" ]
